Repository klaytn/finder-api, pull requests merged in 2024-06, with the labels that each got.

#42 fix: extend transaction and burnt graphs to 30 days
  .gitignore
  module-domain/src/main/kotlin/io/klaytn/finder/service/FinderHomeService.kt
  module-domain/src/test/kotlin/io/klaytn/finder/service/governancecouncil/GovernanceCouncilTest.kt
Labels: documentation

#43 fix: add volume information to klay price data
  module-worker/src/main/kotlin/io/klaytn/finder/worker/infra/client/CoinMarketCapClient.kt
  module-worker/src/main/kotlin/io/klaytn/finder/worker/interfaces/job/KlayPriceJob.kt
  module-worker/src/main/kotlin/io/klaytn/finder/worker/interfaces/rest/api/WorkerController.kt
Labels: enhancement

#44 hotfix: add volume information to klay price data in front
  module-domain/src/main/kotlin/io/klaytn/finder/service/FinderHomeService.kt
  module-domain/src/main/kotlin/io/klaytn/finder/view/model/FinderHome.kt
Labels: fix

#45 feat: papi fetch token info
  .gitignore
  build.gradle.kts
  conf.example.sh
  docs/schema/mysql/scope_set1.sql
  docs/schema/mysql/scope_set4.sql
  module-common/src/main/kotlin/io/klaytn/finder/domain/common/KaiaUserType.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set1/KaiaUser.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set1/KaiaUserLoginHistory.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set1/KaiaUserLoginHistoryRepository.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set1/KaiaUserRepository.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/GovernanceCouncilCategories.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/GovernanceCouncilCategoriesRepository.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/GovernanceCouncilCommunities.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/GovernanceCouncilCommunitiesRepository.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/GovernanceCouncilContracts.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/GovernanceCouncilContractsRepository.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/GovernanceCouncilsInfo.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/GovernanceCouncilsInfoRepository.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/TokenInfo.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/TokenInfoRepository.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/TokenTimeSeries.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/TokenTimeSeriesRepository.kt
  module-domain/src/main/kotlin/io/klaytn/finder/infra/client/KaiaSquareClient.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/config/ClientConfig.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/config/SpringDocConfig.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/infra/client/CoinMarketCapClient.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/KaiaUserController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/mapper/KaiaUserViewMapper.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/mapper/TokenToViewMapper.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/kaiauser/KaiaUserSignInView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/kaiauser/KaiaUserSignupView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/kaiauser/KaiaUserView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/papi/PapiCoinMarketCapController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/papi/PapiGovernanceCouncilController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/papi/PapiTokenController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/GovernanceCouncilInfoService.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/GovernanceCouncilSyncService.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/KaiaUserService.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/papi/CoinMarketCapService.kt
  module-front-api/src/main/resources/application-client.yml
  module-worker/src/main/kotlin/io/klaytn/finder/worker/infra/client/FinderPrivateApiClient.kt
  module-worker/src/main/kotlin/io/klaytn/finder/worker/interfaces/job/GovernanceCouncilInfoSyncJob.kt
  module-worker/src/main/kotlin/io/klaytn/finder/worker/interfaces/job/TokenInfoJob.kt
Labels: feature

#49 I 47/front api/implement email sign up using jwt
  conf.example.sh
  docs/schema/mysql/scope_set1.sql
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set1/KaiaUser.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/KaiaUserController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/mapper/KaiaUserViewMapper.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/KaiaUserService.kt
  module-front-api/src/main/resources/application-client.yml
Labels: enhancement, feature

#51 Initial Implementation of Account Overview API
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set1/KaiaUser.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set1/KaiaUserLoginHistoryRepository.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/KaiaUserController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/mapper/KaiaUserViewMapper.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/kaiauser/KaiaUserAccountView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/kaiauser/KaiaUserChangePasswordView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/kaiauser/KaiaUserDeleteAccountView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/KaiaUserService.kt
Labels: feature

#53 feat: add session id during sign in
  module-domain/src/main/kotlin/io/klaytn/finder/infra/redis/RedisKeyManager.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/KaiaUserController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/mapper/KaiaUserViewMapper.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/kaiauser/KaiaUserSignInView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/KaiaUserService.kt
Labels: feature

#55 Implementing sign out feature
  module-domain/src/main/kotlin/io/klaytn/finder/infra/redis/RedisKeyManager.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/KaiaUserController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/KaiaUserService.kt
Labels: feature

#57 I 56/feat/building guards for user controllers
  module-front-api/src/main/kotlin/io/klaytn/finder/config/WebMvcConfig.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/infra/web/interceptor/KaiaUserSessionInterceptor.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/KaiaUserController.kt
Labels: documentation, feature

#60 Implement api endpoint for fetching gc info
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/GovernanceCouncilController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/mapper/GovernanceCouncilToViewMapper.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/governancecouncil/GovernanceCouncilView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/papi/PapiGovernanceCouncilController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/GovernanceCouncilInfoService.kt
Labels: feature

#61 feat: add price info to token list
  docs/schema/mysql/scope_set4.sql
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/TokenTimeSeries.kt
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/TokenTimeSeriesRepository.kt
  module-domain/src/main/kotlin/io/klaytn/finder/service/ContractService.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/infra/client/CoinMarketCapClient.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/ContractSearchController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/TokenController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/mapper/TokenToViewMapper.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/token/TokenListWithPriceInfoView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/token/TokenPriceInfoView.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/service/papi/CoinMarketCapService.kt
Labels: documentation, enhancement

#63 fix: add price info in token item
  module-domain/src/main/kotlin/io/klaytn/finder/domain/mysql/set4/TokenTimeSeriesRepository.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/TokenController.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/mapper/TokenToViewMapper.kt
  module-front-api/src/main/kotlin/io/klaytn/finder/interfaces/rest/api/view/model/token/TokenItemWithPriceInfoView.kt
Labels: documentation, enhancement
